"""Build a standalone HTML file from a chat session for download."""
from __future__ import annotations

import html
from datetime import datetime, timezone
from typing import Any

from report_builder import TABLE_SECTIONS, _table


def _message_block(role: str, text: str, *, is_html: bool) -> str:
    label = "You" if role == "user" else "Assistant"
    css_role = "user" if role == "user" else "assistant"
    if is_html and role == "assistant":
        body = text
    else:
        body = f"<p>{html.escape(text)}</p>"
    return (
        f'<div class="msg {css_role}">'
        f'<div class="msg-label">{html.escape(label)}</div>'
        f'<div class="msg-body">{body}</div>'
        "</div>"
    )


def build_chat_export_html(
    messages: list[dict[str, Any]],
    summary: dict[str, Any],
    *,
    title: str | None = None,
) -> str:
    """Render a self-contained HTML document (chat transcript + data snapshot)."""
    generated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    doc_title = html.escape(title or "Tree Complaint Chat Report")

    dr = summary.get("date_range", ["—", "—"])
    overview = f"""
    <section class="card">
      <h2>Dataset snapshot</h2>
      <ul>
        <li><strong>Total cases:</strong> {summary.get("total_cases", 0)}</li>
        <li><strong>Total trees:</strong> {summary.get("total_trees", 0)}</li>
        <li><strong>Date range:</strong> {html.escape(str(dr[0]))} → {html.escape(str(dr[1]))}</li>
        <li><strong>Exported:</strong> {generated}</li>
      </ul>
    </section>
    """

    tables = "".join(
        _table(section_title, summary[key])
        for key, section_title in TABLE_SECTIONS
        if key in summary
    )

    transcript = "".join(
        _message_block(
            m.get("role", "assistant"),
            m.get("text", ""),
            is_html=bool(m.get("isHtml") or m.get("is_html")),
        )
        for m in messages
        if m.get("text")
    )

    if not transcript:
        transcript = '<p class="empty">No messages in this session.</p>'

    return f"""<!DOCTYPE html>
<html lang="zh-HK">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{doc_title}</title>
  <style>
    body {{
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      margin: 0;
      background: #f4f6f8;
      color: #1a1a2e;
      line-height: 1.5;
    }}
    .wrap {{ max-width: 900px; margin: 0 auto; padding: 2rem 1.5rem; }}
    h1 {{ margin-top: 0; }}
    .card {{
      background: #fff;
      border: 1px solid #e5e7eb;
      border-radius: 12px;
      padding: 1.25rem;
      margin-bottom: 1rem;
    }}
    table {{ width: 100%; border-collapse: collapse; }}
    th, td {{
      text-align: left;
      padding: 0.5rem 0.75rem;
      border-bottom: 1px solid #e5e7eb;
    }}
    .chat-section h2 {{ margin-top: 0; }}
    .msg {{
      padding: 0.75rem 1rem;
      border-radius: 10px;
      margin-bottom: 0.75rem;
    }}
    .msg.user {{ background: #dbeafe; }}
    .msg.assistant {{ background: #f3f4f6; }}
    .msg-label {{
      font-size: 0.75rem;
      font-weight: 600;
      color: #5c6370;
      margin-bottom: 0.35rem;
    }}
    .msg-body {{ overflow-x: auto; }}
    .footer {{
      font-size: 0.85rem;
      color: #5c6370;
      margin-top: 2rem;
    }}
    @media print {{
      body {{ background: #fff; }}
      .card {{ break-inside: avoid; }}
    }}
  </style>
</head>
<body>
  <div class="wrap">
    <h1>{doc_title}</h1>
    <p>Chat session export with dataset snapshot at time of download.</p>
    {overview}
    {tables}
    <section class="card chat-section">
      <h2>Chat transcript</h2>
      {transcript}
    </section>
    <p class="footer">Generated by Tree Complaint Analyst · {generated}</p>
  </div>
</body>
</html>
"""
